version: '3.8'
services:
  appb:
    build:
      context: "C:\\Users\\dimab\\ru.clevertec.comment"
      dockerfile: Dockerfile
    container_name: container_comment
    ports:
      - 8081:8080
    depends_on:
      db1:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db1:5432/news
      POSTGRES_HOST: db1
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: news
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true